### ISSUE TITLE
Does not produce audio

### ISSUE THREAD

**Issue by Gamegenorator** [Guibibi/CodeRadio-Desktop#1]
Hi, I've only tried the Linux app image but it doesn't seem to play audio, But it does detect what song should be being played and it displays to correct image, but no audio is produced. This happens both on my by Ubuntu 19.04 machine and Zorin OS 15 machine. Does anyone know the cause for this?

**Comment by Guibibi** [comment]
@Gamegenorator Issue is being invistigated right now, sorry for the delay.

**Comment by Guibibi** [comment]
@Gamegenorator Tried the app on a VM of Ubuntu 19.04, and the playback was working for me.
Did you make sure that the audio device that you are using is set as the default audio output?

**Comment by Gamegenorator** [comment]
@Guibibi It wasn't and audio device issue but reinstalling it from a new download file fixed the problem. Sorry for the trouble, shall I close the issue then?

**Comment by Guibibi** [comment]
Ah well glad to hear it works now!

I will indeed close the issue.
